apiVersion: external-secrets.io/v1
#The ClusterSecretStore is a cluster scoped SecretStore that can be referenced by all ExternalSecrets from all namespaces. Use it to offer a central gateway to your secret backend.
kind: ClusterSecretStore
metadata:
  name: vault-one2n-store
spec:
  provider:
    vault:
      # The address of the vault service.
      server: "http://vault-svc.vault-ns.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          # Mount Path is kubernetes meaning 
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets-ns"
