apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: one2n-dev-app-config
  namespace: student-api  # App's Kubernetes namespace
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-one2n-store
    kind: ClusterSecretStore  # ClusterSecretStore works across namespaces
  target:
    name: one2n-dev-app-config
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: one2n/dev/app-config
        property: db_password
    - secretKey: db_url
      remoteRef:
        key: one2n/dev/app-config
        property: db_url
