# ClusterRole: allows the vault-sa service account to perform Kubernetes
# token reviews — required for Vault's Kubernetes authentication method.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.rbac.clusterRole.name }}
  labels:
    app: vault
    {{- include "eso-vault.labels" . | nindent 4 }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
# ClusterRoleBinding: binds vault-sa in vault-ns to the vault-token-review ClusterRole.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.rbac.clusterRoleBinding.name }}
  labels:
    app: vault
    {{- include "eso-vault.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vault.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.rbac.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
