{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  # Gives the Vault pods a Kubernetes identity. Vault's Kubernetes auth method
  # uses this account's token to call the TokenReview API.
  name: {{ include "vault.serviceAccountName" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
{{- end }}
