apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-db
    {{- include "student-app.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgresDb.config.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.postgresDb.config.POSTGRES_DB | quote }}
