apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-statefulset
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-db
    {{- include "student-app.labels" . | nindent 4 }}
spec:
  serviceName: postgres-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      nodeSelector:
        {{- toYaml .Values.postgresDb.nodeSelector | nindent 8 }}
      containers:
        - name: postgres
          image: "{{ .Values.postgresDb.image.repository }}:{{ .Values.postgresDb.image.tag }}"
          imagePullPolicy: {{ .Values.postgresDb.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresDb.dbSecret }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-db-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgresDb.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgresDb.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgresDb.storageSize }}
