# ExternalSecret: syncs DATABASE_URL from Vault into student-db-url-secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: student-api
    {{- include "student-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.dbUrl.targetSecret }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}
        property: {{ .Values.externalSecrets.dbUrl.property }}
---
# ExternalSecret: syncs POSTGRES_PASSWORD from Vault into postgres-db-secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-db-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-db
    {{- include "student-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.dbPassword.targetSecret }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}
        property: {{ .Values.externalSecrets.dbPassword.property }}
---
# ExternalSecret: syncs dockerconfigjson from Vault into dockerhub-secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: student-api
    {{- include "student-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.dockerhub.targetSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}
        property: {{ .Values.externalSecrets.dockerhub.property }}
