# events block generally contains directives that affect the connection processing model of Nginx.
events {
    # Set the maximum number of simultaneous connections that can be handled by each worker process spun up by Nginx. This value can be adjusted based on the expected traffic and server capacity.
    worker_connections 1024;
}

http {
    # Define an upstream block to specify the backend API servers that Nginx will proxy requests to. This allows for load balancing and failover between multiple backend servers.
    upstream api_servers {
        server api1:5000;
        server api2:5000;
    }

    server {
        listen 8080;

        location / {
            # Proxy requests to the upstream API servers
            proxy_pass http://api_servers;
            # Passes orignal domain/hostname to the backend server.
            proxy_set_header Host $host;
            # Passes orignal client IP address to the backend server.
            proxy_set_header X-Real-IP $remote_addr;
            # Passes the original client IP address to the backend server when their are chain of proxies in between.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Passes the original protocol (HTTP or HTTPS) used by the client to the backend server.
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
