apiVersion: v2
name: eso-vault
description: Helm chart for HashiCorp Vault and External Secrets Operator integration
type: application
version: 1.0.0
appVersion: "2.0"
maintainers:
  - name: madhav-wakhare
keywords:
  - vault
  - external-secrets
  - eso
  - secrets-management
