apiVersion: v1
kind: Namespace
metadata:
  name: vault-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: vault-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault-ns
data:
  vault.hcl: |-
    ui = true
    # Disable mlock to allow Vault to run in environments where mlock is not available (e.g., containers), it is strict for 2.0 and above, so we need to set it to true to avoid errors.
    disable_mlock = true 

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "raft" {
      path = "/vault/data"
    }

    api_addr     = "http://vault-svc.vault-ns.svc.cluster.local:8200"
    cluster_addr = "http://vault-svc.vault-ns.svc.cluster.local:8201"

---
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: vault-ns
spec:
  clusterIP: None
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault-ns
spec:
  serviceName: vault-svc
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      nodeSelector:
        type: dependent_services

      securityContext:
        fsGroup: 1000

      initContainers:
      - name: fix-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command:
        - sh
        - -c
        - |
          mkdir -p /vault/data
          chown -R 100:1000 /vault/data
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data

      containers:
      - name: vault
        image: hashicorp/vault:2.0
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        command: ["vault"]
        args: ["server", "-config=/vault/config/vault.hcl"]
        ports:
        - containerPort: 8200
        - containerPort: 8201
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-data
          mountPath: /vault/data

      volumes:
      - name: vault-config
        configMap:
          name: vault-config

  volumeClaimTemplates:
  - metadata:
      name: vault-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard