name: CI Pipeline - SRE Student App

on:
  push:
    branches:
      - develop
      - ci/cd
      - code-improvements
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Dockerfile'
      - 'Makefile'
  pull_request:
    branches:
      - develop
      - ci/cd
      - main
      - code-improvements
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Dockerfile'
      - 'Makefile'
  workflow_dispatch:

jobs:
  ci:
    runs-on: [self-hosted, macOS, ARM64]


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build API (Install Dependencies)
        run: |
          make install

      - name: Perform Code Linting
        run: |
          make lint

      - name: Run Tests
        run: |
          make test

      - name: Set Commit Hash Environment Variable
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          echo "Building Docker image with version ${{ env.COMMIT_HASH }}..."
          IMAGE_NAME=sre-student-api IMAGE_VERSION=${{ env.COMMIT_HASH }} make docker-build

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sre-student-api:${{ env.COMMIT_HASH }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Docker Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/sre-student-api"
          echo "Tagging image for Docker Hub..."
          docker tag sre-student-api:${{ env.COMMIT_HASH }} $DOCKER_IMAGE:${{ env.COMMIT_HASH }}
          
          echo "Pushing image $DOCKER_IMAGE:${{ env.COMMIT_HASH }} to Docker Hub..."
          docker push $DOCKER_IMAGE:${{ env.COMMIT_HASH }}


